Devreview
JoshThomasField/portfolio pull request #5
Opened 2020-09-08 14:30 UTC by JoshThomasField

Happy with the overall structure, design and responsiveness. Just plan to experiment in future iterations.

2020-09-08 14:57 UTC, norayna commented on index.html
> +                    <h3>About me!</h3>
h3 directly below h1 - not advised, for semantic/accessibility purposes it should probably be an h2

https://www.w3.org/WAI/tutorials/page-structure/headings/

2020-09-08 14:57 UTC, norayna commented on index.html
> +            <h1>My Projects!</h1>
Semantically this is less important on the page than the main heading (the first h1) and probably comparably important to the "About me" heading. Therefore it should probably be at the same level and probably an h2

2020-09-08 15:01 UTC, norayna commented on style.css
> +  font-family: Forum;
Provide alternative font e.g.
```
font-family: Forum, serif
```

2020-09-08 15:21 UTC, JoshThomasField commented on index.html
> +                    <h3>About me!</h3>
Thanks Rayna, I have changed this and will have a read through w3. Can I think of anything after h1 as like the level its at? Like...

<div>
          <h2></h2>
</div>
<div>
          <h2></h2>
</div>
<div>
          <div>
                   <h3></h3>
          </div>
</div>
?

2020-09-08 15:23 UTC, mporam requested changes

2020-09-08 15:23 UTC, mporam commented on color-pallet.css
> +/* CSS HEX */
you arent actually using this file at all, why is it here?

2020-09-08 15:23 UTC, mporam commented on index.html
> +                <img class="logo" src="signature (1).png" alt="Logo">
its best to avoid spaces in file names as this wont work on some operating systems

2020-09-08 15:23 UTC, mporam commented on index.html
> +                <a>Home</a>
are these supposed to go somewhere? and say something other than Home?

2020-09-08 15:23 UTC, mporam commented on index.html
> +            <div class="desktop-nav">
duplicating HTML like this is very bad practise, you should be able to use CSS to achieve the visual you want with the same HTML for all platforms

2020-09-08 15:23 UTC, mporam commented on index.html
> +                <img src="https://post.medicalnewstoday.com/wp-content/uploads/sites/3/2020/02/322868_1100-800x825.jpg" alt="project image"/>
best to download all images and put them in your repo, then link to them locally, rather than linking to a random online site which may go down

2020-09-08 15:23 UTC, mporam commented on index.html
> +        <div class="section-divider above-project"></div>
could this be done with a `::after` pseudo element instead?...probably...

2020-09-08 15:23 UTC, mporam commented on index.html
> +                <form action="">
generally it is not advisable to put a contact form on your portfolio, nobody will use it and you wont be able to make it functional with the hosting solution we have, suggest removing and swapping for a text line about downloading your cv or getting in touch via email or something

2020-09-08 15:23 UTC, mporam commented on index.html
> +                <li><a href="https://www.facebook.com/"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
currently these go to generic places. dont forget to update the links.
also, do you really want your facebook here?

2020-09-08 15:23 UTC, mporam commented on style.css
> +/*
dont need this comment, can be removed

2020-09-08 15:23 UTC, mporam commented on style.css
> +body {
you should be an empty line break between each CSS selector:
```
selector {
    property: value;
}

selector {
```

2020-09-08 15:23 UTC, mporam commented on style.css
> +  background-color: #0d1321ff;
browser support for 8 digit hex codes isnt great:
https://caniuse.com/css-rrggbbaa
rgba is designed for this

2020-09-08 15:23 UTC, mporam commented on style.css
> +.display-container h1:before {
psuedo elements are supposed to be selected using two `::`

2020-09-08 15:23 UTC, mporam commented on style.css
> +  25%  {color: yellow;}
use hex values where possible

2020-09-08 15:23 UTC, mporam commented on style.css
> +  margin: 20px 0px;
0 values dont need px... 0 anything is still 0

2020-09-08 15:23 UTC, mporam commented on style.css
> +.social-footer .social-footer-icons li:last-of-type {
better to do this with a class

2020-09-08 15:41 UTC, JoshThomasField commented on index.html
> +                <a>Home</a>
Was putting them in for JS later but have just removed them now as they aren't necessary. Haven't bothered creating page anchors as I can't add smooth scroll without JS

2020-09-08 15:48 UTC, norayna commented
I noticed that when the page width is less than 600px the project title & description for each project become very very small

2020-09-08 15:51 UTC, norayna commented
As the width of the page increases, white space appears on both sides of the dog:
![image](https://user-images.githubusercontent.com/25844355/92499164-76298180-f1f3-11ea-9016-e24647a4ea5d.png)

2020-09-08 15:57 UTC, norayna commented
The dog picture in project items doesn't preserve its original aspect ratio:

![image](https://user-images.githubusercontent.com/25844355/92499800-357e3800-f1f4-11ea-91d0-cb8f2a536bd8.png) ![image](https://user-images.githubusercontent.com/25844355/92499859-475fdb00-f1f4-11ea-8dea-d6533e4cc4e1.png)

2020-09-08 16:04 UTC, JoshThomasField commented on index.html
> +                <img src="https://post.medicalnewstoday.com/wp-content/uploads/sites/3/2020/02/322868_1100-800x825.jpg" alt="project image"/>
Will change these later, just used them so you could interact with them for testing.

2020-09-09 09:02 UTC, mporam requested changes

2020-09-09 10:02 UTC, JoshThomasField commented on index.html
>          <div class="section-divider bottom"></div>
I have just deleted this now.

2020-09-09 10:03 UTC, JoshThomasField commented on index.html
> +                <li><a href="https://github.com/JoshThomasField"><i class="fa fa-github"></i></i></a></li>
Deleted the extra closing </i>

2020-09-09 10:09 UTC, mporam approved these changes

2020-09-09 10:10 UTC, merged